apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cod-go 
  janus-idp.io/tekton: cod-go
  backstage.io/kubernetes-id: cod-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cod-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  